In [1]:
import numpy as np

In [6]:
a = np.array([10,20,30,40,50,60,70])
b = np.array([1,2,3,4,5,6,7])
a, b

(array([10, 20, 30, 40, 50, 60, 70]), array([1, 2, 3, 4, 5, 6, 7]))

In [7]:
a + b

array([11, 22, 33, 44, 55, 66, 77])

In [8]:
a * b

array([ 10,  40,  90, 160, 250, 360, 490])

In [9]:
a * 2

array([ 20,  40,  60,  80, 100, 120, 140])

In [10]:
a ** 3 

array([  1000,   8000,  27000,  64000, 125000, 216000, 343000],
      dtype=int32)

In [12]:
b *= 5
b

array([ 5, 10, 15, 20, 25, 30, 35])

In [13]:
b /= 3

TypeError: No loop matching the specified signature and casting was found for ufunc true_divide

In [14]:
b = b / 3
b

array([ 1.66666667,  3.33333333,  5.        ,  6.66666667,  8.33333333,
       10.        , 11.66666667])

In [16]:
arr1 = np.array([[1,2,3]])
arr1

array([[1, 2, 3]])

In [20]:
arr2 = arr1.T # transpose()
arr2

array([[1],
       [2],
       [3]])

In [21]:
arr1 + arr2

array([[2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]])

In [22]:
arr1 * arr2

array([[1, 2, 3],
       [2, 4, 6],
       [3, 6, 9]])

In [23]:
np.dot(arr1, arr2)

array([[14]])

#### Wybieranie danych z tabeli

In [24]:
np.random.seed(0)
arr = np.random.randint(-10, 11, (7,8) )
arr

array([[  2,   5, -10,  -7,  -7,  -3,  -1,   9],
       [  8,  -6,  -4,   2,  -9,  -4,  -3,   4],
       [  7,  -5,   3,  -2,  -1,  10,   9,   6],
       [  9,  -5,   5,   5, -10,   8,  -7,   7],
       [  9,   9,   9,   4,  -3, -10,  -9,  -1],
       [-10,   0,  10,  -7,   1,   8,  -8, -10],
       [-10,  -6,  -5,  -4,  -2,  10,   7,   5]])

In [26]:
arr[6], arr[-1]

(array([-10,  -6,  -5,  -4,  -2,  10,   7,   5]),
 array([-10,  -6,  -5,  -4,  -2,  10,   7,   5]))

In [28]:
# wiersz nr 2 i 3 oraz co 2-ga kolumna
arr[ 1:3 , ::2 ]

array([[ 8, -4, -9, -3],
       [ 7,  3, -1,  9]])

In [29]:
# tylko pierwszy i ostatni
arr[ [0,-1] ]

array([[  2,   5, -10,  -7,  -7,  -3,  -1,   9],
       [-10,  -6,  -5,  -4,  -2,  10,   7,   5]])

In [31]:
# tylko ostatnia kolumna
arr[ : , -1 ]

array([  9,   4,   6,   7,  -1, -10,   5])

In [32]:
arr.T[-1]

array([  9,   4,   6,   7,  -1, -10,   5])

In [33]:
# tylko kolumna nr 2 i przedostania
arr[ : , [1,-2] ]

array([[ 5, -1],
       [-6, -3],
       [-5,  9],
       [-5, -7],
       [ 9, -9],
       [ 0, -8],
       [-6,  7]])

In [35]:
arr[ -1, -1]

5

In [37]:
for row in arr:
    print(row)
    print("="*60)

[  2   5 -10  -7  -7  -3  -1   9]
[ 8 -6 -4  2 -9 -4 -3  4]
[ 7 -5  3 -2 -1 10  9  6]
[  9  -5   5   5 -10   8  -7   7]
[  9   9   9   4  -3 -10  -9  -1]
[-10   0  10  -7   1   8  -8 -10]
[-10  -6  -5  -4  -2  10   7   5]


In [38]:
for row in arr.T:
    print(row)
    print("="*60)

[  2   8   7   9   9 -10 -10]
[ 5 -6 -5 -5  9  0 -6]
[-10  -4   3   5   9  10  -5]
[-7  2 -2  5  4 -7 -4]
[ -7  -9  -1 -10  -3   1  -2]
[ -3  -4  10   8 -10   8  10]
[-1 -3  9 -7 -9 -8  7]
[  9   4   6   7  -1 -10   5]


In [39]:
lista1 = [1,2,3,4]
lista2 = lista1

In [42]:
lista2[0] = -999

In [43]:
lista1

[-999, 2, 3, 4]

In [44]:
lista1 = [1,2,3,4]
lista2 = lista1.copy()

In [45]:
lista2[0] = -999
lista1, lista2

([1, 2, 3, 4], [-999, 2, 3, 4])

In [48]:
arr2 = arr # to nie jest klonowanie tablicy

In [49]:
arr2 = np.copy(arr)

In [50]:
id(arr) , id(arr2)

(2608340482544, 2608340689040)

#### Porównanie szybkości list vs numpy

In [52]:
%%timeit -r 10 -n 100
[x**2 for x in range(10_000)]

4.05 ms ± 256 µs per loop (mean ± std. dev. of 10 runs, 100 loops each)


In [54]:
%%timeit -r 10 -n 100
np.arange(10_000)**2

37.2 µs ± 16.6 µs per loop (mean ± std. dev. of 10 runs, 100 loops each)


In [55]:
4.05E-3 / 37.2E-6 

108.87096774193547

In [56]:
arr

array([[  2,   5, -10,  -7,  -7,  -3,  -1,   9],
       [  8,  -6,  -4,   2,  -9,  -4,  -3,   4],
       [  7,  -5,   3,  -2,  -1,  10,   9,   6],
       [  9,  -5,   5,   5, -10,   8,  -7,   7],
       [  9,   9,   9,   4,  -3, -10,  -9,  -1],
       [-10,   0,  10,  -7,   1,   8,  -8, -10],
       [-10,  -6,  -5,  -4,  -2,  10,   7,   5]])

In [57]:
arr[ [0,-1] ]

array([[  2,   5, -10,  -7,  -7,  -3,  -1,   9],
       [-10,  -6,  -5,  -4,  -2,  10,   7,   5]])

In [58]:
arr[ [-1,0] ]

array([[-10,  -6,  -5,  -4,  -2,  10,   7,   5],
       [  2,   5, -10,  -7,  -7,  -3,  -1,   9]])