In [29]:
import numpy as np

In [30]:
class Perceptron:
    
    def __init__(self):
        """ Inicjalizacja wag dla perceptronu """
        np.random.seed(0)
        self.weights = np.random.random((3,1))
        
    def sigmoid(self, x):
        """ Funkcja aktywacji sigmoid """
        return 1/(1+np.exp(-x))
    
    def d_sigmoid(self, x):
        """ Pochodna do f. aktywacji """
        return x*(1-x)
    
    def propagation(self, inputs):
        """ Propagacji danych i wag """
        return self.sigmoid( np.dot(inputs, self.weights) )
    
    def back_propagation(self, propagation_result, train_input, train_output):
        """ Prosty algorytm prop. wstecznej """
        error = train_output - propagation_result
        self.weights += np.dot( train_input.T, error*self.d_sigmoid(propagation_result) )
        
    def train(self, train_input, train_output, epochs):
        """ Funkcja trenująca """
        for _ in range(epochs):
            result = self.propagation(train_input)
            self.back_propagation(result, train_input, train_output)

In [31]:
model = Perceptron()

X = np.array([
    [1,1,0], [1,1,1], [1,1,0], [0,1,1], [0,1,0]
])
y = np.array([ [0, 1, 0, 1, 0 ] ]).T

In [32]:
print(model.weights)
print("="*60)
model.train(X, y, 10_000)
print(model.weights)

[[0.5488135 ]
 [0.71518937]
 [0.60276338]]
[[-0.42737095]
 [-4.68671741]
 [ 9.87413863]]


In [33]:
model.train(X, y, 10_000)

In [34]:
X_test = np.array([
    [1,1,0], [1,1,1], [1,1,0], [0,1,1], [0,1,0], [0,0,1], [1,0,0]
])
#y = np.array([ [0, 1, 0, 1, 0 ] ]).T
for x in X_test:
    print(f"{x} = {np.round(model.propagation(x),0)}")

[1 1 0] = [0.]
[1 1 1] = [1.]
[1 1 0] = [0.]
[0 1 1] = [1.]
[0 1 0] = [0.]
[0 0 1] = [1.]
[1 0 0] = [0.]
